#!/usr/bin/env python

import sys
import subprocess
import shlex

base = ['env', 'XMODIFIERS=@im=fcitx', 'st', '-c', 'Terminal',\
	 '-f', 'Source Code Pro:size=10:dpi=192', '-g', '100x30', '-e', 'tmux']

args = sys.argv[1:]

if len(args) >= 2 and args[0] == '-e':
	command = ' '.join([shlex.quote(arg) for arg in args[1:]])
	subprocess.run(base + ['-c', command])
else:
	subprocess.run(base)
